### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
You will be asked to add this for [your RFP with F-Droid](https://gitlab.com/fdroid/rfp/-/issues/1845). Until that is processed, starting in about 2 hours you can find your app [listed with my repo](https://apt.izzysoft.de/fdroid/index/apk/com.soumikshah.investmenttracker). Should you want to link there e.g. from your Readme, be welcome to use [this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for visuals :smiley:

### CODE REVIEW

**Comment by soumikshah** [comment]
Thank you for taking out time for pushing initial fastlane structure. I'm looking forward to check my app listed with your repo. Will definitely use your badge in Readme. Thank you!

**Comment by IzzySoft** [comment]
Thanks Soumik! Listing is online now. I usually remove it again about 10 days after an app becomes available at f-droid.org – unless the author (here: you) requests to keep it there. Some arguments (pro/con) can be found in [this FAQ](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) – you've got plenty of time to decide, as it will take at least a week or two to get your app listed at F-Droid.

And thanks for adding the badge! The listing with my repo gives you an idea what my Fastlane contribution will look like :smiley: I'll now enable that in my repo for your app, so potential future updates you might make will be reflected. My updater checks once a day for new tags with APKs attached and then will pick the APK – and cross-check for updates in Fastlane.

PS: Next steps, once the RFP is "approved", will be moving to a merge request to establish your app with F-Droid. At that point there should be a tag in your repo here with Fastlane inside, as F-Droid builds from the tag and Fastlane is pulled from the same tag.

**Comment by IzzySoft** [comment]
PS: I've just announced Plutus being available via my repo now. One **IMPORTANT** thing you should remember is to **always increase `versionCode` before tagging a release** – your app still identifies with `versionCode: 1`. Otherwise F-Droid would not pull any updates – and even with my repo, users would receive no update notifications as Android will say: "1=1 – this is the same version, no actions needed".

**Comment by soumikshah** [comment]
Thank you so much for the information! I saw the listing, really happy it was able to go online in such a short time. Really appreciate it! 

I created new tag with new release of the application which includes fastlane and new apk file in my repo.

And really grateful you caught version code problem. I forgot to change it for the app when it came out of alpha release.

**Comment by IzzySoft** [comment]
Great, thanks! Just triggered the update manually: works :smile:

Fun fact: you name the APKs `com.soumikshah.plutus.apk` while the real package name is `com.soumikshah.investmenttracker`. Unimportant detail maybe. Just don't get the idea of switching package names after the app was published, as that would force all users to re-install while losing their configuration and other data (unless there's an export/import option).

As the tag is there now (and the `versionCode` issue fixed), the RFP can be processed further. No idea why the bot was that silent, it usually is more verbose.

**Comment by IzzySoft** [comment]
PS: [there you go](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9733), let's see whether issuebot is more talkative when it got decent metadata to work on :smile:

**Comment by soumikshah** [comment]
> Great, thanks! Just triggered the update manually: works :smile:
> 
> Fun fact: you name the APKs `com.soumikshah.plutus.apk` while the real package name is `com.soumikshah.investmenttracker`. Unimportant detail maybe. Just don't get the idea of switching package names after the app was published, as that would force all users to re-install while losing their configuration and other data (unless there's an export/import option).
> 
> As the tag is there now (and the `versionCode` issue fixed), the RFP can be processed further. No idea why the bot was that silent, it usually is more verbose.

Thank you.

Haha yeah I realized that. I was initially going to call the app investment tracker. And then after alpha testing, didn't feel it right to release it without an actual name. So just gave it a name. Making it easier for people to get to my name by searching Plutus. For the next application, I need to come up with a name before starting with Android Studio 😜.

Yeah I saw other people's issue and the bot was way more verbose. Adding different labels.

**Comment by IzzySoft** [comment]
The bot is sometimes hard to predict (or to understand why it failed/missed things). Let's see what it reports on the MR. I'm optimistic the 3rd round now will succeed: the error with missing Java 11 is a frequent one (until the build env was finally updated) so I know how to deal with it. I expect issuebot to show up there in about 30..45min (it usually kicks in about 1h after the first commit was added).

**Comment by IzzySoft** [comment]
Finalizing – merge imminent (auto-merge when pipelines succeed). Welcome aboard! Merge completed. The question usually asked at this place, and answered: [How long does it take for my app to show up on website and client?](https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client) Pointer: The current build cycle is just about to complete, so Plutus should be part of the next.

Last question: Do you agree to the "default" of your app being removed again from my repo about 10d after it became available at F-Droid – or do you want me to keep it in my repo then? Both are available options, their background linked from my second comment above. Just let me know when you decided. Time to act will be in about two weeks from now. And you can re-decide anytime: it's easily removed later, or added back.

**Comment by soumikshah** [comment]
Awesome!!

Thank you so much for all your help. Really appreciate it!

Yeah I'll let you know in about 2 weeks about what to do about app being available in your repo. I'm just too excited right now to decide. It's feels awesome to have your app listed on open source repositories.

**Comment by IzzySoft** [comment]
Yupp, understandable. Party first, part-or-stay later. Enjoy the moment(s)! I've put a note with your metadata to check here again when the time comes.

And glad to help! I enjoyed bringing your app in. Nice helpful tool, and completely offline _o/

**Comment by soumikshah** [comment]
Thank you for the kind words. 

I wanted to buy you a beer for your help with the fastlane and fdroid. Wasn't able to because of bank restrictions to transfer money internationally. So instead bought your book through kindle. Appreciate your help.

**Comment by IzzySoft** [comment]
Thanks! That's even a win-win then if you can read German (let me know then to send you the latest version). As for international transfers, I've heard good things about Transferwise (actually even received some transfers via them). Senders told me they are fast (which I can confirm: same day delivery) and a lot cheaper than their banks :smile:

**Comment by IzzySoft** [comment]
The end is near! Ahem, I mean: the two weeks are gone. Time to decide. Did you, @soumikshah?

**Comment by soumikshah** [comment]
Hello IzzySoft, thank you for the reminder and sorry for the late reply. I've decided to let my app be part of izzyOnDroid repo,

**Comment by IzzySoft** [comment]
Then welcome for a permanent residence! With the next sync in about 2h, the description in my repo viewer will point out that your app is available in both, the F-Droid repo and mine.

**Comment by soumikshah** [comment]
Thank you so much, IzzySoft!

**Pull request merged**
